title: Your Name
email: your-email@example.com
description: >- 
  A short description of yourself and your website.
baseurl: ""
url: "https://username.github.io"
theme: jekyll-theme-minimal # Change this to the theme you chose

# Add your photo
photo: Me.jpg
